### ISSUE TITLE
Multi-stage workflows need to be able to launch new jobs from compute nodes

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-aws-marketplace#50]
Flight needs an option to allow jobs to be launched from within jobs to support multi-stage workflows

**Comment by sierra-tango-echo** [comment]
@wdm78 so thats basically add compute nodes as submit hosts?

**Comment by wdm78** [comment]
Yep - not sure if we want this to be an option, or the default for compute nodes?

**Comment by mjtko** [comment]
This may be related to #45 — could be another `alces configure scheduler`/`scheduler:` configuration parameter.

**Comment by mjtko** [comment]
Fixed in https://github.com/alces-software/clusterware/commit/1f753e9be267b96b6c5a62818a8ac0569fe5f104

Can now do this by default by supplying appropriate `config.yml` keys (`cluster`->`scheduler`->`submission`), or manually enable via `alces configure scheduler submission` command.  Possible values are `all` (all nodes), `master` (master node only), `none` (no nodes nowhere nohow).

**Comment by vlj91** [comment]
This is included in `2016.3`
